"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path # Importation de la classe Path depuis le module pathlib pour gérer les chemins de fichiers et de répertoires de manière plus pratique et lisible.

# Construisez les chemins à l'intérieur du projet comme ceci : BASE_DIR / 'sous-dossier'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# AVERTISSEMENT DE SÉCURITÉ : keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f@=238ypx%uo$^zhax)!9&9-v+gkxvux3yb3#oe1s5*y&$h0m5' #ajout d'une clé secrète pour la sécurité de l'application Django (à ne pas divulguer en production !)

# AVERTISSEMENT DE SÉCURITÉ : ne pas exécuter avec le debug activé en production !
DEBUG = True

ALLOWED_HOSTS = [] 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', #Active l'interface d'administration de Django
    'django.contrib.auth', # Gère les utilisateurs et leur authentification de Django
    'django.contrib.contenttypes', # Utilisé pour relier les modèles de Django entre eux
    'django.contrib.sessions', # Gère les sessions de Django (le fait de rester connecté d'une page à une autre)
    'django.contrib.messages', # Permet d'afficher des messages à l'utilisateur (ex: "Votre compte a été créé avec succès !")
    'django.contrib.staticfiles', # Gère les fichiers statiques de Django (CSS, JS, images...)
    'sites', #Ajoute l'application "site" à notre projet Django
    'rest_framework', #Ajoute le framework Django REST pour créer des API RESTful
    'rest_framework.authtoken', #Ajoute le système d'authentification par token de Django REST
    'corsheaders', #Ajoute le middleware CORS pour gérer les requêtes cross-origin
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware', 
    'django.middleware.common.CommonMiddleware', 
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'sites.middleware.SousDomaineMiddleware',  # Ajout du middleware pour gérer les sous-domaines
]


Extensions = {'.html', '.css', '.js', '.png', '.jpg', '.jpeg', '.svg', '.ico'}

CORS_ALLOW_ALL_ORIGINS = True

ALLOWED_HOSTS = ['lvh.me', 'localhost', '127.0.0.1']

ROOT_URLCONF = 'config.urls'

TEMPLATES = [ # Définit les paramètres pour le moteur de template de Django
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application' #Indique le point d’entrée technique utilisé par le serveur pour faire
#tourner l’application


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ # Définit les validateurs de mot de passe pour l'authentification
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/' # Définit l'URL pour les fichiers statiques

import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')