# Generated by Django 6.0.7 on 2026-07-31 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('taille', models.PositiveIntegerField()),
                ('date_version', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date_version'],
            },
        ),
        migrations.CreateModel(
            name='SiteStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('visites', models.PositiveIntegerField(default=0)),
                ('pages_vues', models.JSONField(default=dict)),
                ('visiteurs_uniques', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sitefile',
            name='hash_contenu',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sitefile',
            name='taille',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitefile',
            name='type_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_publication',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='publication',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='sous_domaine',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sitefile',
            name='filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['publication', 'date_publication'], name='sites_site_publica_c2d30e_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['utilisateur', 'date_creation'], name='sites_site_utilisa_5be182_idx'),
        ),
        migrations.AddIndex(
            model_name='sitefile',
            index=models.Index(fields=['site', 'filename'], name='sites_sitef_site_id_333f62_idx'),
        ),
        migrations.AddField(
            model_name='sitefileversion',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitefileversion',
            name='fichier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='sites.sitefile'),
        ),
        migrations.AddField(
            model_name='sitestatistique',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='sitefileversion',
            index=models.Index(fields=['fichier', 'date_version'], name='sites_sitef_fichier_225ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='sitestatistique',
            index=models.Index(fields=['site', 'date'], name='sites_sites_site_id_09f87e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sitestatistique',
            unique_together={('site', 'date')},
        ),
    ]
